
platform_enseignants_add:
    path:    /enseignant/add
    defaults: { _controller: KPPlatformBundle:Enseignant:add }

platform_enseignants_show:
    path:    /enseignant/show
    defaults: { _controller: KPPlatformBundle:Enseignant:show }
